import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// All 2026 AFL players from AFL Fantasy
const players = [
  { name: "Jordan Dawson", team: "Adelaide Crows", position: "MID", avg: 110.2, games: 23 },
  { name: "Rory Laird", team: "Adelaide Crows", position: "DEF", avg: 92.6, games: 20 },
  { name: "Reilly O'Brien", team: "Adelaide Crows", position: "RUC", avg: 90.9, games: 23 },
  { name: "Izak Rankine", team: "Adelaide Crows", position: "MID/FWD", avg: 87.2, games: 22 },
  { name: "Riley Thilthorpe", team: "Adelaide Crows", position: "FWD", avg: 82.9, games: 23 },
  { name: "Jake Soligo", team: "Adelaide Crows", position: "MID", avg: 82.8, games: 23 },
  { name: "Ben Keays", team: "Adelaide Crows", position: "FWD", avg: 79.3, games: 23 },
  { name: "James Peatling", team: "Adelaide Crows", position: "MID", avg: 77.7, games: 21 },
  { name: "Josh Worrell", team: "Adelaide Crows", position: "DEF", avg: 75.3, games: 23 },
  { name: "Lachlan Sholl", team: "Adelaide Crows", position: "MID", avg: 53.0, games: 5 },
  { name: "Wayne Milera", team: "Adelaide Crows", position: "DEF", avg: 72.0, games: 22 },
  { name: "Alex Neal-Bullen", team: "Adelaide Crows", position: "FWD", avg: 69.4, games: 23 },
  { name: "Mitchell Hinge", team: "Adelaide Crows", position: "DEF", avg: 67.1, games: 22 },
  { name: "Daniel Curtin", team: "Adelaide Crows", position: "MID", avg: 65.2, games: 23 },
  { name: "Callum Ah Chee", team: "Adelaide Crows", position: "FWD", avg: 62.5, games: 22 },
  { name: "Josh Rachele", team: "Adelaide Crows", position: "FWD", avg: 62.5, games: 13 },
  { name: "Sam Berry", team: "Adelaide Crows", position: "MID", avg: 62.4, games: 17 },
  { name: "Taylor Walker", team: "Adelaide Crows", position: "FWD", avg: 61.5, games: 21 },
  { name: "Isaac Cumming", team: "Adelaide Crows", position: "MID", avg: 61.4, games: 22 },
  { name: "Darcy Fogarty", team: "Adelaide Crows", position: "FWD", avg: 59.3, games: 22 },
  { name: "Luke Nankervis", team: "Adelaide Crows", position: "MID", avg: 45.1, games: 7 },
  { name: "Mark Keane", team: "Adelaide Crows", position: "DEF", avg: 54.8, games: 23 },
  { name: "Max Michalanney", team: "Adelaide Crows", position: "DEF", avg: 54.8, games: 19 },
  { name: "Chayce Jones", team: "Adelaide Crows", position: "MID", avg: 23.8, games: 5 },
  { name: "Billy Dowling", team: "Adelaide Crows", position: "MID", avg: 53.0, games: 1 },
  { name: "Luke Pedlar", team: "Adelaide Crows", position: "FWD", avg: 45.6, games: 7 },
  { name: "Zac Taylor", team: "Adelaide Crows", position: "FWD", avg: 40.9, games: 15 },
  { name: "Nick Murray", team: "Adelaide Crows", position: "DEF", avg: 37.7, games: 10 },
  { name: "James Borlase", team: "Adelaide Crows", position: "DEF", avg: 27.0, games: 2 },
  { name: "Brayden Cook", team: "Adelaide Crows", position: "MID", avg: 30.0, games: 3 },
  { name: "Finnbar Maley", team: "Adelaide Crows", position: "FWD", avg: 35.7, games: 7 },
  { name: "Hugh Bond", team: "Adelaide Crows", position: "DEF", avg: 30.0, games: 4 },
  { name: "Sid Draper", team: "Adelaide Crows", position: "MID", avg: 29.3, games: 10 },
  { name: "Jordon Butts", team: "Adelaide Crows", position: "DEF", avg: 26.3, games: 10 },
  { name: "Josh Dunkley", team: "Brisbane Lions", position: "MID", avg: 107.5, games: 23 },
  { name: "Hugh McCluggage", team: "Brisbane Lions", position: "MID", avg: 102.2, games: 23 },
  { name: "Dayne Zorko", team: "Brisbane Lions", position: "DEF", avg: 101.5, games: 23 },
  { name: "Will Ashcroft", team: "Brisbane Lions", position: "MID", avg: 95.5, games: 23 },
  { name: "Lachie Neale", team: "Brisbane Lions", position: "MID", avg: 94.6, games: 20 },
  { name: "Jarrod Berry", team: "Brisbane Lions", position: "MID", avg: 85.0, games: 21 },
  { name: "Zac Bailey", team: "Brisbane Lions", position: "MID", avg: 83.5, games: 22 },
  { name: "Jaspa Fletcher", team: "Brisbane Lions", position: "DEF", avg: 83.0, games: 23 },
  { name: "Darcy Wilmot", team: "Brisbane Lions", position: "DEF", avg: 79.6, games: 23 },
  { name: "Levi Ashcroft", team: "Brisbane Lions", position: "MID", avg: 74.4, games: 23 },
  { name: "Cam Rayner", team: "Brisbane Lions", position: "FWD", avg: 70.1, games: 23 },
  { name: "Sam Draper", team: "Brisbane Lions", position: "RUC", avg: 82.0, games: 5 },
  { name: "Darcy Fort", team: "Brisbane Lions", position: "RUC", avg: 69.2, games: 17 },
  { name: "Harris Andrews", team: "Brisbane Lions", position: "DEF", avg: 62.2, games: 23 },
  { name: "Noah Answerth", team: "Brisbane Lions", position: "DEF", avg: 57.9, games: 17 },
  { name: "Logan Morris", team: "Brisbane Lions", position: "FWD", avg: 57.7, games: 22 },
  { name: "Ryan Lester", team: "Brisbane Lions", position: "DEF", avg: 57.3, games: 22 },
  { name: "Eric Hipwood", team: "Brisbane Lions", position: "FWD", avg: 54.9, games: 22 },
  { name: "Jack Payne", team: "Brisbane Lions", position: "DEF", avg: 54.2, games: 13 },
  { name: "Keidean Coleman", team: "Brisbane Lions", position: "DEF", avg: 73.0, games: 1 },
  { name: "Charlie Cameron", team: "Brisbane Lions", position: "FWD", avg: 53.3, games: 21 },
  { name: "Conor McKenna", team: "Brisbane Lions", position: "FWD", avg: 26.0, games: 5 },
  { name: "Oscar Allen", team: "Brisbane Lions", position: "FWD", avg: 49.8, games: 12 },
  { name: "Kai Lohmann", team: "Brisbane Lions", position: "FWD", avg: 46.3, games: 14 },
  { name: "Bruce Reville", team: "Brisbane Lions", position: "MID", avg: 43.9, games: 10 },
  { name: "Sam Marshall", team: "Brisbane Lions", position: "MID", avg: 46.0, games: 7 },
  { name: "Darcy Gardiner", team: "Brisbane Lions", position: "DEF", avg: 41.6, games: 14 },
  { name: "Tom Doedee", team: "Brisbane Lions", position: "DEF", avg: 47.0, games: 1 },
  { name: "Henry Smith", team: "Brisbane Lions", position: "FWD", avg: 42.0, games: 2 },
  { name: "Ty Gallop", team: "Brisbane Lions", position: "FWD", avg: 33.0, games: 2 },
  { name: "James Tunstill", team: "Brisbane Lions", position: "MID", avg: 30.7, games: 3 },
  { name: "Will McLachlan", team: "Brisbane Lions", position: "FWD", avg: 23.3, games: 6 },
  { name: "Luke Beecken", team: "Brisbane Lions", position: "MID", avg: 10.0, games: 1 },
  { name: "George Hewett", team: "Carlton", position: "MID", avg: 98.9, games: 23 },
  { name: "Adam Cerra", team: "Carlton", position: "MID", avg: 95.1, games: 19 },
  { name: "Sam Walsh", team: "Carlton", position: "MID", avg: 93.1, games: 14 },
  { name: "Patrick Cripps", team: "Carlton", position: "MID", avg: 88.8, games: 23 },
  { name: "Harry McKay", team: "Carlton", position: "FWD", avg: 78.3, games: 12 },
  { name: "Oliver Hollands", team: "Carlton", position: "DEF", avg: 76.2, games: 23 },
  { name: "Nick Haynes", team: "Carlton", position: "DEF", avg: 75.7, games: 23 },
  { name: "Blake Acres", team: "Carlton", position: "MID", avg: 73.7, games: 19 },
  { name: "Adam Saad", team: "Carlton", position: "DEF", avg: 67.0, games: 21 },
  { name: "Marc Pittonet", team: "Carlton", position: "RUC", avg: 70.3, games: 7 },
  { name: "Lachlan Cowan", team: "Carlton", position: "DEF", avg: 63.4, games: 14 },
  { name: "Mitch McGovern", team: "Carlton", position: "DEF", avg: 62.6, games: 17 },
  { name: "Jacob Weitering", team: "Carlton", position: "DEF", avg: 61.5, games: 23 },
  { name: "Zac Williams", team: "Carlton", position: "FWD", avg: 61.3, games: 19 },
  { name: "Cooper Lord", team: "Carlton", position: "MID", avg: 60.0, games: 21 },
  { name: "Oliver Florent", team: "Carlton", position: "MID", avg: 60.0, games: 16 },
  { name: "Francis Evans", team: "Carlton", position: "FWD", avg: 58.7, games: 10 },
  { name: "Ben Ainsworth", team: "Carlton", position: "FWD", avg: 58.6, games: 22 },
  { name: "Matthew Cottrell", team: "Carlton", position: "MID", avg: 66.2, games: 6 },
  { name: "Brodie Kemp", team: "Carlton", position: "FWD", avg: 47.6, games: 5 },
  { name: "Will Hayward", team: "Carlton", position: "FWD", avg: 55.8, games: 21 },
  { name: "Lachie Fogarty", team: "Carlton", position: "FWD", avg: 55.7, games: 20 },
  { name: "Campbell Chesser", team: "Carlton", position: "MID", avg: 64.5, games: 4 },
  { name: "Jesse Motlop", team: "Carlton", position: "FWD", avg: 50.8, games: 23 },
  { name: "Matthew Carroll", team: "Carlton", position: "DEF", avg: 49.5, games: 17 },
  { name: "Lewis Young", team: "Carlton", position: "DEF", avg: 47.0, games: 13 },
  { name: "Jordan Boyd", team: "Carlton", position: "DEF", avg: 32.7, games: 3 },
  { name: "Flynn Young", team: "Carlton", position: "FWD", avg: 45.6, games: 8 },
  { name: "Harry O'Farrell", team: "Carlton", position: "DEF", avg: 47.0, games: 6 },
  { name: "Ashton Moir", team: "Carlton", position: "FWD", avg: 41.9, games: 9 },
  { name: "Billy Wilson", team: "Carlton", position: "DEF", avg: 49.0, games: 4 },
  { name: "Liam Reidy", team: "Carlton", position: "RUC", avg: 37.0, games: 1 },
  { name: "Lucas Camporeale", team: "Carlton", position: "MID", avg: 44.0, games: 3 },
  { name: "Hudson O'Keeffe", team: "Carlton", position: "FWD", avg: 38.4, games: 5 },
  { name: "Nick Daicos", team: "Collingwood", position: "MID", avg: 108.1, games: 23 },
  { name: "Darcy Cameron", team: "Collingwood", position: "RUC", avg: 102.0, games: 23 },
  { name: "Josh Daicos", team: "Collingwood", position: "DEF", avg: 94.2, games: 23 },
  { name: "Scott Pendlebury", team: "Collingwood", position: "MID", avg: 86.6, games: 20 },
  { name: "Steele Sidebottom", team: "Collingwood", position: "MID", avg: 86.2, games: 21 },
  { name: "Jack Crisp", team: "Collingwood", position: "MID", avg: 84.2, games: 23 },
  { name: "Jordan De Goey", team: "Collingwood", position: "MID", avg: 52.7, games: 9 },
  { name: "Ned Long", team: "Collingwood", position: "MID", avg: 77.0, games: 23 },
  { name: "Lachie Schultz", team: "Collingwood", position: "FWD", avg: 76.6, games: 14 },
  { name: "Jamie Elliott", team: "Collingwood", position: "FWD", avg: 67.8, games: 23 },
  { name: "Patrick Lipinski", team: "Collingwood", position: "MID", avg: 66.9, games: 21 },
  { name: "Dan Houston", team: "Collingwood", position: "DEF", avg: 66.8, games: 19 },
  { name: "Brayden Maynard", team: "Collingwood", position: "DEF", avg: 66.4, games: 18 },
  { name: "Harry Perryman", team: "Collingwood", position: "DEF", avg: 63.0, games: 23 },
  { name: "Isaac Quaynor", team: "Collingwood", position: "DEF", avg: 60.0, games: 23 },
  { name: "Daniel McStay", team: "Collingwood", position: "FWD", avg: 56.6, games: 18 },
  { name: "Beau McCreery", team: "Collingwood", position: "FWD", avg: 54.2, games: 17 },
  { name: "Jeremy Howe", team: "Collingwood", position: "DEF", avg: 51.9, games: 18 },
  { name: "Tim Membrey", team: "Collingwood", position: "FWD", avg: 51.8, games: 21 },
  { name: "Edward Allan", team: "Collingwood", position: "MID", avg: 48.4, games: 13 },
  { name: "Bobby Hill", team: "Collingwood", position: "FWD", avg: 46.1, games: 14 },
  { name: "Jack Buller", team: "Collingwood", position: "FWD", avg: 47.2, games: 9 },
  { name: "Darcy Moore", team: "Collingwood", position: "DEF", avg: 44.4, games: 20 },
  { name: "Lachlan Sullivan", team: "Collingwood", position: "FWD", avg: 43.9, games: 14 },
  { name: "Billy Frampton", team: "Collingwood", position: "DEF", avg: 42.4, games: 14 },
  { name: "Roan Steele", team: "Collingwood", position: "MID", avg: 46.0, games: 3 },
  { name: "William Hayes", team: "Collingwood", position: "FWD", avg: 45.0, games: 2 },
  { name: "Wil Parker", team: "Collingwood", position: "DEF", avg: 31.7, games: 3 },
  { name: "Reef McInnes", team: "Collingwood", position: "DEF", avg: 34.3, games: 3 },
  { name: "Charlie West", team: "Collingwood", position: "FWD", avg: 19.0, games: 1 },
  { name: "Jye Caldwell", team: "Essendon", position: "MID", avg: 103.6, games: 11 },
  { name: "Zach Merrett", team: "Essendon", position: "MID", avg: 102.8, games: 22 },
  { name: "Nic Martin", team: "Essendon", position: "MID", avg: 97.4, games: 16 },
  { name: "Archie Roberts", team: "Essendon", position: "DEF", avg: 85.9, games: 23 },
  { name: "Mason Redman", team: "Essendon", position: "DEF", avg: 85.8, games: 19 },
  { name: "Brayden Fiorini", team: "Essendon", position: "MID", avg: 85.8, games: 16 },
  { name: "Xavier Duursma", team: "Essendon", position: "MID", avg: 78.8, games: 22 },
  { name: "Sam Durham", team: "Essendon", position: "MID", avg: 78.4, games: 20 },
  { name: "Zach Reid", team: "Essendon", position: "DEF", avg: 75.4, games: 10 },
  { name: "Andrew McGrath", team: "Essendon", position: "DEF", avg: 74.9, games: 23 },
  { name: "Peter Wright", team: "Essendon", position: "FWD", avg: 73.9, games: 19 },
  { name: "Darcy Parish", team: "Essendon", position: "MID", avg: 85.3, games: 3 },
  { name: "Kyle Langford", team: "Essendon", position: "FWD", avg: 49.9, games: 9 },
  { name: "Jordan Ridley", team: "Essendon", position: "DEF", avg: 63.2, games: 10 },
  { name: "Jaxon Prior", team: "Essendon", position: "DEF", avg: 62.5, games: 23 },
  { name: "Angus Clarke", team: "Essendon", position: "DEF", avg: 62.2, games: 14 },
  { name: "Nick Bryan", team: "Essendon", position: "RUC", avg: 57.8, games: 4 },
  { name: "Archie Perkins", team: "Essendon", position: "FWD", avg: 57.0, games: 21 },
  { name: "Jade Gresham", team: "Essendon", position: "FWD", avg: 53.6, games: 19 },
  { name: "Nate Caddy", team: "Essendon", position: "FWD", avg: 53.5, games: 17 },
  { name: "Harrison Jones", team: "Essendon", position: "MID", avg: 50.0, games: 7 },
  { name: "Zak Johnson", team: "Essendon", position: "DEF", avg: 50.4, games: 9 },
  { name: "Isaac Kako", team: "Essendon", position: "FWD", avg: 47.0, games: 23 },
  { name: "Archer May", team: "Essendon", position: "FWD", avg: 51.3, games: 7 },
  { name: "Saad El-Hawli", team: "Essendon", position: "MID", avg: 44.2, games: 9 },
  { name: "Matt Guelfi", team: "Essendon", position: "FWD", avg: 42.4, games: 12 },
  { name: "Elijah Tsatas", team: "Essendon", position: "MID", avg: 49.8, games: 5 },
  { name: "Ben McKay", team: "Essendon", position: "DEF", avg: 39.0, games: 10 },
  { name: "Lachlan Blakiston", team: "Essendon", position: "DEF", avg: 38.0, games: 11 },
  { name: "Lewis Hayes", team: "Essendon", position: "DEF", avg: 52.0, games: 1 },
  { name: "Vigo Visentini", team: "Essendon", position: "RUC", avg: 49.5, games: 2 },
  { name: "Liam McMahon", team: "Essendon", position: "FWD", avg: 35.3, games: 7 },
  { name: "Thomas Edwards", team: "Essendon", position: "FWD", avg: 40.0, games: 2 },
  { name: "Jayden Nguyen", team: "Essendon", position: "DEF", avg: 35.2, games: 5 },
  { name: "Archer Day-Wicks", team: "Essendon", position: "FWD", avg: 33.0, games: 5 },
  { name: "Rhys Unwin", team: "Essendon", position: "FWD", avg: 28.7, games: 3 },
  { name: "Andrew Brayshaw", team: "Fremantle", position: "MID", avg: 101.0, games: 23 },
  { name: "Luke Jackson", team: "Fremantle", position: "RUC", avg: 94.9, games: 20 },
  { name: "Caleb Serong", team: "Fremantle", position: "MID", avg: 92.4, games: 23 },
  { name: "Jordan Clark", team: "Fremantle", position: "DEF", avg: 90.2, games: 23 },
  { name: "Hayden Young", team: "Fremantle", position: "MID", avg: 62.5, games: 8 },
  { name: "Luke Ryan", team: "Fremantle", position: "DEF", avg: 81.9, games: 23 },
  { name: "Matthew Johnson", team: "Fremantle", position: "MID", avg: 70.5, games: 18 },
  { name: "Shai Bolton", team: "Fremantle", position: "MID", avg: 70.0, games: 22 },
  { name: "Nathan O'Driscoll", team: "Fremantle", position: "MID", avg: 64.4, games: 13 },
  { name: "Corey Wagner", team: "Fremantle", position: "MID", avg: 64.2, games: 17 },
  { name: "Sean Darcy", team: "Fremantle", position: "RUC", avg: 64.3, games: 16 },
  { name: "Jaeger O'Meara", team: "Fremantle", position: "MID", avg: 63.2, games: 13 },
  { name: "Josh Treacy", team: "Fremantle", position: "FWD", avg: 62.7, games: 23 },
  { name: "Michael Frederick", team: "Fremantle", position: "FWD", avg: 58.8, games: 23 },
  { name: "Neil Erasmus", team: "Fremantle", position: "MID", avg: 56.8, games: 15 },
  { name: "Murphy Reid", team: "Fremantle", position: "FWD", avg: 55.4, games: 23 },
  { name: "Karl Worner", team: "Fremantle", position: "DEF", avg: 55.2, games: 22 },
  { name: "Sam Switkowski", team: "Fremantle", position: "FWD", avg: 55.1, games: 17 },
  { name: "Patrick Voss", team: "Fremantle", position: "FWD", avg: 54.8, games: 19 },
  { name: "Judd McVee", team: "Fremantle", position: "DEF", avg: 54.5, games: 17 },
  { name: "Heath Chapman", team: "Fremantle", position: "DEF", avg: 53.6, games: 22 },
  { name: "Bailey Banfield", team: "Fremantle", position: "DEF", avg: 53.0, games: 20 },
  { name: "Jeremy Sharp", team: "Fremantle", position: "MID", avg: 48.1, games: 14 },
  { name: "Mason Cox", team: "Fremantle", position: "RUC", avg: 42.8, games: 8 },
  { name: "Alex Pearce", team: "Fremantle", position: "DEF", avg: 45.9, games: 15 },
  { name: "Oscar McDonald", team: "Fremantle", position: "DEF", avg: 49.4, games: 7 },
  { name: "Brennan Cox", team: "Fremantle", position: "DEF", avg: 44.4, games: 23 },
  { name: "Brandon Walker", team: "Fremantle", position: "DEF", avg: 34.0, games: 2 },
  { name: "Jye Amiss", team: "Fremantle", position: "FWD", avg: 41.0, games: 23 },
  { name: "Isaiah Dudley", team: "Fremantle", position: "FWD", avg: 36.7, games: 15 },
  { name: "Cooper Simpson", team: "Fremantle", position: "DEF", avg: 41.0, games: 3 },
  { name: "Joshua Draper", team: "Fremantle", position: "DEF", avg: 31.5, games: 11 },
  { name: "Bailey Smith", team: "Geelong", position: "MID", avg: 116.3, games: 20 },
  { name: "Max Holmes", team: "Geelong", position: "MID", avg: 100.9, games: 23 },
  { name: "Gryan Miers", team: "Geelong", position: "FWD", avg: 93.8, games: 21 },
  { name: "Shaun Mannagh", team: "Geelong", position: "FWD", avg: 88.1, games: 20 },
  { name: "Tom Atkins", team: "Geelong", position: "MID", avg: 87.8, games: 23 },
  { name: "Jeremy Cameron", team: "Geelong", position: "FWD", avg: 83.6, games: 23 },
  { name: "Tom Stewart", team: "Geelong", position: "DEF", avg: 80.5, games: 18 },
  { name: "Zach Guthrie", team: "Geelong", position: "DEF", avg: 76.7, games: 23 },
  { name: "James Worpel", team: "Geelong", position: "MID", avg: 73.8, games: 18 },
  { name: "Jack Martin", team: "Geelong", position: "FWD", avg: 73.0, games: 10 },
  { name: "Oliver Dempsey", team: "Geelong", position: "MID", avg: 72.7, games: 23 },
  { name: "Mark Blicavs", team: "Geelong", position: "RUC", avg: 70.9, games: 22 },
  { name: "Lawson Humphries", team: "Geelong", position: "DEF", avg: 70.5, games: 22 },
  { name: "Mark O'Connor", team: "Geelong", position: "DEF", avg: 64.5, games: 22 },
  { name: "Rhys Stanley", team: "Geelong", position: "RUC", avg: 64.4, games: 18 },
  { name: "Patrick Dangerfield", team: "Geelong", position: "FWD", avg: 63.6, games: 20 },
  { name: "Tyson Stengle", team: "Geelong", position: "FWD", avg: 61.7, games: 21 },
  { name: "Shannon Neale", team: "Geelong", position: "FWD", avg: 61.3, games: 22 },
  { name: "Jack Henry", team: "Geelong", position: "DEF", avg: 60.2, games: 18 },
  { name: "Jack Bowes", team: "Geelong", position: "MID", avg: 58.8, games: 18 },
  { name: "Connor O'Sullivan", team: "Geelong", position: "DEF", avg: 57.5, games: 22 },
  { name: "Sam De Koning", team: "Geelong", position: "DEF", avg: 55.9, games: 20 },
  { name: "Brad Close", team: "Geelong", position: "FWD", avg: 54.0, games: 23 },
  { name: "Jed Bews", team: "Geelong", position: "DEF", avg: 60.8, games: 4 },
  { name: "Mitch Knevitt", team: "Geelong", position: "MID", avg: 51.9, games: 7 },
  { name: "Oisin Mullin", team: "Geelong", position: "DEF", avg: 46.6, games: 22 },
  { name: "Jhye Clark", team: "Geelong", position: "MID", avg: 37.7, games: 7 },
  { name: "Oliver Henry", team: "Geelong", position: "FWD", avg: 41.0, games: 15 },
  { name: "George Stevens", team: "Geelong", position: "MID", avg: 52.5, games: 2 },
  { name: "Oliver Wiltshire", team: "Geelong", position: "FWD", avg: 34.5, games: 2 },
  { name: "Matt Rowell", team: "Gold Coast", position: "MID", avg: 101.2, games: 23 },
  { name: "Noah Anderson", team: "Gold Coast", position: "MID", avg: 99.5, games: 23 },
  { name: "Jarrod Witts", team: "Gold Coast", position: "RUC", avg: 92.4, games: 22 },
  { name: "Touk Miller", team: "Gold Coast", position: "MID", avg: 91.0, games: 21 },
  { name: "John Noble", team: "Gold Coast", position: "DEF", avg: 90.9, games: 23 },
  { name: "Christian Petracca", team: "Gold Coast", position: "MID", avg: 90.4, games: 23 },
  { name: "Joel Jeffrey", team: "Gold Coast", position: "DEF", avg: 75.7, games: 23 },
  { name: "Daniel Rioli", team: "Gold Coast", position: "DEF", avg: 71.2, games: 18 },
  { name: "Bailey Humphrey", team: "Gold Coast", position: "MID", avg: 68.3, games: 21 },
  { name: "Wil Powell", team: "Gold Coast", position: "DEF", avg: 66.9, games: 23 },
  { name: "Bodhi Uwland", team: "Gold Coast", position: "DEF", avg: 63.1, games: 23 },
  { name: "Ben Long", team: "Gold Coast", position: "FWD", avg: 62.2, games: 22 },
  { name: "Sam Clohesy", team: "Gold Coast", position: "MID", avg: 62.1, games: 14 },
  { name: "Ned Moyle", team: "Gold Coast", position: "RUC", avg: 51.7, games: 3 },
  { name: "Alex Davies", team: "Gold Coast", position: "MID", avg: 62.0, games: 6 },
  { name: "Mac Andrew", team: "Gold Coast", position: "DEF", avg: 56.0, games: 22 },
  { name: "Will Graham", team: "Gold Coast", position: "FWD", avg: 55.3, games: 8 },
  { name: "Lachie Weller", team: "Gold Coast", position: "MID", avg: 54.4, games: 17 },
  { name: "Jy Farrar", team: "Gold Coast", position: "FWD", avg: 61.2, games: 6 },
  { name: "Sam Collins", team: "Gold Coast", position: "DEF", avg: 51.9, games: 20 },
  { name: "Ben King", team: "Gold Coast", position: "FWD", avg: 50.3, games: 23 },
  { name: "Ethan Read", team: "Gold Coast", position: "FWD", avg: 43.2, games: 19 },
  { name: "Jed Walter", team: "Gold Coast", position: "FWD", avg: 37.9, games: 16 },
  { name: "Nick Holman", team: "Gold Coast", position: "MID", avg: 36.7, games: 16 },
  { name: "Charlie Ballard", team: "Gold Coast", position: "DEF", avg: 30.0, games: 1 },
  { name: "Lachlan Gulbin", team: "Gold Coast", position: "FWD", avg: 50.0, games: 1 },
  { name: "Jake Rogers", team: "Gold Coast", position: "FWD", avg: 27.3, games: 9 },
  { name: "Ben Jepson", team: "Gold Coast", position: "MID", avg: 38.0, games: 1 },
  { name: "Oscar Adams", team: "Gold Coast", position: "DEF", avg: 26.4, games: 8 },
  { name: "Leonardo Lombard", team: "Gold Coast", position: "FWD", avg: 23.0, games: 4 },
  { name: "Lachie Whitfield", team: "GWS", position: "DEF", avg: 105.2, games: 22 },
  { name: "Lachie Ash", team: "GWS", position: "DEF", avg: 100.1, games: 23 },
  { name: "Finn Callaghan", team: "GWS", position: "MID", avg: 99.0, games: 20 },
  { name: "Tom Green", team: "GWS", position: "MID", avg: 97.5, games: 22 },
  { name: "Clayton Oliver", team: "GWS", position: "MID", avg: 89.7, games: 22 },
  { name: "Toby Greene", team: "GWS", position: "FWD", avg: 81.0, games: 21 },
  { name: "Josh Kelly", team: "GWS", position: "MID", avg: 80.9, games: 14 },
  { name: "Harry Himmelberg", team: "GWS", position: "DEF", avg: 78.2, games: 23 },
  { name: "Brent Daniels", team: "GWS", position: "FWD", avg: 47.7, games: 6 },
  { name: "Stephen Coniglio", team: "GWS", position: "MID", avg: 59.4, games: 9 },
  { name: "Connor Idun", team: "GWS", position: "DEF", avg: 72.7, games: 23 },
  { name: "Kieren Briggs", team: "GWS", position: "RUC", avg: 70.4, games: 19 },
  { name: "Jake Riccardi", team: "GWS", position: "RUC", avg: 68.2, games: 19 },
  { name: "Ryan Angwin", team: "GWS", position: "MID", avg: 68.3, games: 9 },
  { name: "Jayden Laverde", team: "GWS", position: "DEF", avg: 65.6, games: 14 },
  { name: "Jesse Hogan", team: "GWS", position: "FWD", avg: 65.3, games: 15 },
  { name: "Darcy Jones", team: "GWS", position: "FWD", avg: 62.1, games: 22 },
  { name: "Sam Taylor", team: "GWS", position: "DEF", avg: 61.9, games: 19 },
  { name: "Aaron Cadman", team: "GWS", position: "FWD", avg: 59.4, games: 23 },
  { name: "Callum Brown", team: "GWS", position: "FWD", avg: 57.9, games: 21 },
  { name: "Xavier O'Halloran", team: "GWS", position: "MID", avg: 57.5, games: 22 },
  { name: "Toby Bedford", team: "GWS", position: "MID", avg: 56.2, games: 22 },
  { name: "Jack Buckley", team: "GWS", position: "DEF", avg: 55.2, games: 19 },
  { name: "Jake Stringer", team: "GWS", position: "FWD", avg: 53.5, games: 14 },
  { name: "Harry Rowston", team: "GWS", position: "MID", avg: 51.9, games: 10 },
  { name: "Harvey Thomas", team: "GWS", position: "FWD", avg: 51.2, games: 17 },
  { name: "Nicholas Madden", team: "GWS", position: "RUC", avg: 63.3, games: 3 },
  { name: "Joe Fonti", team: "GWS", position: "DEF", avg: 49.7, games: 16 },
  { name: "Conor Stone", team: "GWS", position: "DEF", avg: 50.9, games: 7 },
  { name: "Toby McMullin", team: "GWS", position: "MID", avg: 42.3, games: 11 },
  { name: "Leek Aleer", team: "GWS", position: "DEF", avg: 36.3, games: 12 },
  { name: "Cody Angove", team: "GWS", position: "FWD", avg: 42.0, games: 4 },
  { name: "Max Gruzewski", team: "GWS", position: "FWD", avg: 37.9, games: 7 },
  { name: "James Leake", team: "GWS", position: "DEF", avg: 31.7, games: 3 },
  { name: "Josaia Delana", team: "GWS", position: "FWD", avg: 28.0, games: 3 },
  { name: "Lloyd Meek", team: "Hawthorn", position: "RUC", avg: 93.3, games: 22 },
  { name: "Karl Amon", team: "Hawthorn", position: "DEF", avg: 88.6, games: 22 },
  { name: "Jai Newcombe", team: "Hawthorn", position: "MID", avg: 86.4, games: 23 },
  { name: "Dylan Moore", team: "Hawthorn", position: "FWD", avg: 81.8, games: 23 },
  { name: "James Sicily", team: "Hawthorn", position: "DEF", avg: 79.1, games: 20 },
  { name: "Jarman Impey", team: "Hawthorn", position: "DEF", avg: 77.2, games: 21 },
  { name: "Will Day", team: "Hawthorn", position: "MID", avg: 86.8, games: 6 },
  { name: "Josh Ward", team: "Hawthorn", position: "MID", avg: 75.9, games: 22 },
  { name: "Jack Ginnivan", team: "Hawthorn", position: "FWD", avg: 75.3, games: 22 },
  { name: "Jack Gunston", team: "Hawthorn", position: "FWD", avg: 74.1, games: 20 },
  { name: "Conor Nash", team: "Hawthorn", position: "MID", avg: 74.1, games: 19 },
  { name: "Harry Morrison", team: "Hawthorn", position: "MID", avg: 70.9, games: 20 },
  { name: "Massimo D'Ambrosio", team: "Hawthorn", position: "MID", avg: 70.4, games: 23 },
  { name: "Josh Battle", team: "Hawthorn", position: "DEF", avg: 70.3, games: 23 },
  { name: "Josh Weddle", team: "Hawthorn", position: "DEF", avg: 69.7, games: 15 },
  { name: "Connor Macdonald", team: "Hawthorn", position: "FWD", avg: 68.0, games: 21 },
  { name: "Blake Hardwick", team: "Hawthorn", position: "DEF", avg: 62.7, games: 23 },
  { name: "Cam Mackenzie", team: "Hawthorn", position: "MID", avg: 62.5, games: 12 },
  { name: "Mabior Chol", team: "Hawthorn", position: "FWD", avg: 59.8, games: 21 },
  { name: "Jack Scrimshaw", team: "Hawthorn", position: "DEF", avg: 53.8, games: 13 },
  { name: "Nick Watson", team: "Hawthorn", position: "FWD", avg: 49.9, games: 22 },
  { name: "Finn Maginness", team: "Hawthorn", position: "FWD", avg: 48.9, games: 13 },
  { name: "Sam Butler", team: "Hawthorn", position: "MID", avg: 59.0, games: 3 },
  { name: "Ned Reeves", team: "Hawthorn", position: "RUC", avg: 63.0, games: 1 },
  { name: "Max Ramsden", team: "Hawthorn", position: "FWD", avg: 53.3, games: 4 },
  { name: "Henry Hustwaite", team: "Hawthorn", position: "MID", avg: 51.5, games: 4 },
  { name: "Tom Barrass", team: "Hawthorn", position: "DEF", avg: 41.1, games: 22 },
  { name: "Calsher Dear", team: "Hawthorn", position: "FWD", avg: 42.9, games: 8 },
  { name: "Mitch Lewis", team: "Hawthorn", position: "FWD", avg: 45.5, games: 6 },
  { name: "Bailey Macdonald", team: "Hawthorn", position: "DEF", avg: 18.8, games: 6 },
  { name: "Max Gawn", team: "Melbourne", position: "RUC", avg: 113.3, games: 23 },
  { name: "Jack Steele", team: "Melbourne", position: "MID", avg: 95.9, games: 21 },
  { name: "Christian Salem", team: "Melbourne", position: "DEF", avg: 93.0, games: 23 },
  { name: "Jack Viney", team: "Melbourne", position: "MID", avg: 88.4, games: 18 },
  { name: "Kysaiah Pickett", team: "Melbourne", position: "MID", avg: 87.3, games: 20 },
  { name: "Jake Bowey", team: "Melbourne", position: "DEF", avg: 86.4, games: 23 },
  { name: "Trent Rivers", team: "Melbourne", position: "DEF", avg: 82.4, games: 23 },
  { name: "Ed Langdon", team: "Melbourne", position: "MID", avg: 74.2, games: 23 },
  { name: "Steven May", team: "Melbourne", position: "DEF", avg: 72.1, games: 16 },
  { name: "Kade Chandler", team: "Melbourne", position: "FWD", avg: 68.7, games: 23 },
  { name: "Bayley Fritsch", team: "Melbourne", position: "FWD", avg: 63.4, games: 22 },
  { name: "Harvey Langford", team: "Melbourne", position: "MID", avg: 62.7, games: 22 },
  { name: "Tom Sparrow", team: "Melbourne", position: "FWD", avg: 61.1, games: 22 },
  { name: "Tom McDonald", team: "Melbourne", position: "DEF", avg: 59.5, games: 17 },
  { name: "Brody Mihocek", team: "Melbourne", position: "FWD", avg: 58.7, games: 20 },
  { name: "Daniel Turner", team: "Melbourne", position: "DEF", avg: 58.2, games: 19 },
  { name: "Jake Melksham", team: "Melbourne", position: "FWD", avg: 54.5, games: 19 },
  { name: "Caleb Windsor", team: "Melbourne", position: "DEF", avg: 53.9, games: 17 },
  { name: "Changkuoth Jiath", team: "Melbourne", position: "DEF", avg: 53.6, games: 17 },
  { name: "Jacob van Rooyen", team: "Melbourne", position: "FWD", avg: 53.7, games: 16 },
  { name: "Koltyn Tholstrup", team: "Melbourne", position: "FWD", avg: 33.8, games: 9 },
  { name: "Jake Lever", team: "Melbourne", position: "DEF", avg: 52.3, games: 8 },
  { name: "Xavier Lindsay", team: "Melbourne", position: "MID", avg: 52.4, games: 18 },
  { name: "Jai Culley", team: "Melbourne", position: "MID", avg: 59.8, games: 4 },
  { name: "Harrison Petty", team: "Melbourne", position: "FWD", avg: 48.1, games: 19 },
  { name: "Blake Howes", team: "Melbourne", position: "DEF", avg: 43.8, games: 12 },
  { name: "Max Heath", team: "Melbourne", position: "RUC", avg: 43.8, games: 4 },
  { name: "Jack Henderson", team: "Melbourne", position: "FWD", avg: 41.4, games: 5 },
  { name: "Harry Sharp", team: "Melbourne", position: "FWD", avg: 30.6, games: 18 },
  { name: "Aidan Johnson", team: "Melbourne", position: "FWD", avg: 30.8, games: 5 },
  { name: "Bailey Laurie", team: "Melbourne", position: "FWD", avg: 12.0, games: 1 },
  { name: "Matthew Jefferson", team: "Melbourne", position: "FWD", avg: 28.7, games: 7 },
  { name: "Jed Adams", team: "Melbourne", position: "DEF", avg: 27.0, games: 1 },
  { name: "Harry Sheezel", team: "North Melbourne", position: "MID", avg: 109.2, games: 23 },
  { name: "Tristan Xerri", team: "North Melbourne", position: "RUC", avg: 105.0, games: 20 },
  { name: "Luke Davies-Uniacke", team: "North Melbourne", position: "MID", avg: 87.7, games: 22 },
  { name: "Tom Powell", team: "North Melbourne", position: "MID", avg: 86.9, games: 23 },
  { name: "Luke Parker", team: "North Melbourne", position: "MID", avg: 86.7, games: 22 },
  { name: "Caleb Daniel", team: "North Melbourne", position: "DEF", avg: 85.0, games: 23 },
  { name: "Jy Simpkin", team: "North Melbourne", position: "MID", avg: 83.1, games: 21 },
  { name: "Colby McKercher", team: "North Melbourne", position: "DEF", avg: 78.5, games: 23 },
  { name: "Zac Fisher", team: "North Melbourne", position: "FWD", avg: 42.3, games: 7 },
  { name: "Paul Curtis", team: "North Melbourne", position: "FWD", avg: 71.0, games: 19 },
  { name: "George Wardlaw", team: "North Melbourne", position: "MID", avg: 68.0, games: 13 },
  { name: "Dylan Stephens", team: "North Melbourne", position: "MID", avg: 63.9, games: 22 },
  { name: "Luke McDonald", team: "North Melbourne", position: "DEF", avg: 60.7, games: 15 },
  { name: "Nick Larkey", team: "North Melbourne", position: "FWD", avg: 58.6, games: 17 },
  { name: "Cameron Zurhaar", team: "North Melbourne", position: "FWD", avg: 57.6, games: 22 },
  { name: "Aidan Corr", team: "North Melbourne", position: "DEF", avg: 54.9, games: 10 },
  { name: "Finn O'Sullivan", team: "North Melbourne", position: "DEF", avg: 53.7, games: 22 },
  { name: "Jack Darling", team: "North Melbourne", position: "FWD", avg: 51.1, games: 22 },
  { name: "Riley Hardeman", team: "North Melbourne", position: "DEF", avg: 48.1, games: 17 },
  { name: "Charlie Comben", team: "North Melbourne", position: "DEF", avg: 47.7, games: 20 },
  { name: "Cooper Trembath", team: "North Melbourne", position: "FWD", avg: 60.3, games: 3 },
  { name: "Toby Pink", team: "North Melbourne", position: "DEF", avg: 47.3, games: 17 },
  { name: "Griffin Logue", team: "North Melbourne", position: "DEF", avg: 47.1, games: 16 },
  { name: "Bailey Scott", team: "North Melbourne", position: "MID", avg: 44.7, games: 12 },
  { name: "Jacob Konstanty", team: "North Melbourne", position: "FWD", avg: 43.6, games: 23 },
  { name: "Cooper Harvey", team: "North Melbourne", position: "FWD", avg: 46.3, games: 7 },
  { name: "Charlie Spargo", team: "North Melbourne", position: "FWD", avg: 40.2, games: 10 },
  { name: "Wil Dawson", team: "North Melbourne", position: "DEF", avg: 42.6, games: 5 },
  { name: "Jackson Archer", team: "North Melbourne", position: "DEF", avg: 27.0, games: 3 },
  { name: "Robert Hansen Jr", team: "North Melbourne", position: "MID", avg: 33.2, games: 12 },
  { name: "Zane Duursma", team: "North Melbourne", position: "DEF", avg: 31.0, games: 10 },
  { name: "Zac Banch", team: "North Melbourne", position: "FWD", avg: 31.5, games: 4 },
  { name: "Matt Whitlock", team: "North Melbourne", position: "DEF", avg: 23.5, games: 2 },
  { name: "Callum Coleman-Jones", team: "North Melbourne", position: "RUC", avg: 3.0, games: 1 },
  { name: "Connor Rozee", team: "Port Adelaide", position: "DEF", avg: 104.1, games: 21 },
  { name: "Zak Butters", team: "Port Adelaide", position: "MID", avg: 99.9, games: 20 },
  { name: "Ollie Wines", team: "Port Adelaide", position: "MID", avg: 89.5, games: 20 },
  { name: "Jason Horne-Francis", team: "Port Adelaide", position: "MID", avg: 82.2, games: 15 },
  { name: "Jordon Sweet", team: "Port Adelaide", position: "RUC", avg: 81.4, games: 19 },
  { name: "Miles Bergman", team: "Port Adelaide", position: "DEF", avg: 78.3, games: 19 },
  { name: "Kane Farrell", team: "Port Adelaide", position: "DEF", avg: 78.0, games: 21 },
  { name: "Willem Drew", team: "Port Adelaide", position: "MID", avg: 75.1, games: 23 },
  { name: "Jase Burgoyne", team: "Port Adelaide", position: "DEF", avg: 74.2, games: 20 },
  { name: "Mitch Georgiades", team: "Port Adelaide", position: "FWD", avg: 69.3, games: 23 },
  { name: "Joe Richards", team: "Port Adelaide", position: "FWD", avg: 65.3, games: 22 },
  { name: "Sam Powell-Pepper", team: "Port Adelaide", position: "FWD", avg: 64.2, games: 16 },
  { name: "Aliir Aliir", team: "Port Adelaide", position: "DEF", avg: 57.0, games: 22 },
  { name: "Mani Liddy", team: "Port Adelaide", position: "MID", avg: 58.7, games: 9 },
  { name: "Darcy Byrne-Jones", team: "Port Adelaide", position: "FWD", avg: 56.5, games: 22 },
  { name: "Jack Lukosius", team: "Port Adelaide", position: "FWD", avg: 47.3, games: 7 },
  { name: "Ewan Mackinlay", team: "Port Adelaide", position: "MID", avg: 75.0, games: 1 },
  { name: "Ivan Soldo", team: "Port Adelaide", position: "RUC", avg: 26.0, games: 1 },
  { name: "Jacob Wehr", team: "Port Adelaide", position: "DEF", avg: 52.3, games: 14 },
  { name: "Dante Visentini", team: "Port Adelaide", position: "RUC", avg: 53.9, games: 8 },
  { name: "Jackson Mead", team: "Port Adelaide", position: "MID", avg: 51.3, games: 20 },
  { name: "Logan Evans", team: "Port Adelaide", position: "DEF", avg: 49.4, games: 10 },
  { name: "Esava Ratugolea", team: "Port Adelaide", position: "DEF", avg: 49.2, games: 13 },
  { name: "Christian Moraes", team: "Port Adelaide", position: "MID", avg: 47.4, games: 14 },
  { name: "Brandon Zerk-Thatcher", team: "Port Adelaide", position: "DEF", avg: 47.3, games: 13 },
  { name: "Josh Sinn", team: "Port Adelaide", position: "DEF", avg: 45.4, games: 20 },
  { name: "Lachie Jones", team: "Port Adelaide", position: "DEF", avg: 43.1, games: 18 },
  { name: "Will Lorenz", team: "Port Adelaide", position: "MID", avg: 47.3, games: 6 },
  { name: "Corey Durdin", team: "Port Adelaide", position: "FWD", avg: 40.5, games: 16 },
  { name: "Joe Berry", team: "Port Adelaide", position: "FWD", avg: 39.6, games: 12 },
  { name: "Jack Whitlock", team: "Port Adelaide", position: "FWD", avg: 42.8, games: 4 },
  { name: "Ollie Lord", team: "Port Adelaide", position: "FWD", avg: 29.4, games: 15 },
  { name: "Harrison Ramm", team: "Port Adelaide", position: "DEF", avg: 35.0, games: 1 },
  { name: "Tom Cochrane", team: "Port Adelaide", position: "FWD", avg: 32.0, games: 3 },
  { name: "Tim Taranto", team: "Richmond", position: "MID", avg: 93.9, games: 21 },
  { name: "Toby Nankervis", team: "Richmond", position: "RUC", avg: 91.1, games: 22 },
  { name: "Jayden Short", team: "Richmond", position: "DEF", avg: 87.0, games: 15 },
  { name: "Jacob Hopper", team: "Richmond", position: "MID", avg: 84.3, games: 23 },
  { name: "Sam Banks", team: "Richmond", position: "DEF", avg: 79.2, games: 22 },
  { name: "Dion Prestia", team: "Richmond", position: "MID", avg: 78.8, games: 12 },
  { name: "Nick Vlastuin", team: "Richmond", position: "DEF", avg: 77.3, games: 22 },
  { name: "Jack Ross", team: "Richmond", position: "MID", avg: 73.1, games: 23 },
  { name: "Kane McAuliffe", team: "Richmond", position: "MID", avg: 73.6, games: 5 },
  { name: "Nathan Broad", team: "Richmond", position: "DEF", avg: 60.9, games: 22 },
  { name: "Rhyan Mansell", team: "Richmond", position: "FWD", avg: 58.4, games: 20 },
  { name: "Seth Campbell", team: "Richmond", position: "FWD", avg: 58.4, games: 22 },
  { name: "Ben Miller", team: "Richmond", position: "DEF", avg: 57.8, games: 23 },
  { name: "Tyler Sonsie", team: "Richmond", position: "MID", avg: 57.6, games: 16 },
  { name: "Tom Brown", team: "Richmond", position: "DEF", avg: 57.1, games: 23 },
  { name: "Hugo Ralphsmith", team: "Richmond", position: "MID", avg: 56.7, games: 12 },
  { name: "Luke Trainor", team: "Richmond", position: "DEF", avg: 55.0, games: 21 },
  { name: "Sam Lalor", team: "Richmond", position: "FWD", avg: 54.1, games: 11 },
  { name: "Noah Balta", team: "Richmond", position: "DEF", avg: 52.7, games: 13 },
  { name: "Tom Lynch", team: "Richmond", position: "FWD", avg: 52.5, games: 16 },
  { name: "James Trezise", team: "Richmond", position: "MID", avg: 46.4, games: 16 },
  { name: "Taj Hotton", team: "Richmond", position: "FWD", avg: 50.9, games: 7 },
  { name: "Maurice Rioli", team: "Richmond", position: "FWD", avg: 41.5, games: 13 },
  { name: "Kaleb Smith", team: "Richmond", position: "DEF", avg: 42.4, games: 8 },
  { name: "Thomas Sims", team: "Richmond", position: "FWD", avg: 37.5, games: 11 },
  { name: "Steely Green", team: "Richmond", position: "FWD", avg: 36.3, games: 18 },
  { name: "Campbell Gray", team: "Richmond", position: "DEF", avg: 44.7, games: 3 },
  { name: "Jonty Faull", team: "Richmond", position: "FWD", avg: 35.3, games: 16 },
  { name: "Mykelti Lefau", team: "Richmond", position: "FWD", avg: 11.0, games: 1 },
  { name: "Samson Ryan", team: "Richmond", position: "RUC", avg: 42.0, games: 2 },
  { name: "Harry Armstrong", team: "Richmond", position: "FWD", avg: 32.4, games: 8 },
  { name: "Josh Gibcus", team: "Richmond", position: "DEF", avg: 25.0, games: 1 },
  { name: "Liam Fawcett", team: "Richmond", position: "FWD", avg: 22.0, games: 1 },
  { name: "Jasper Alger", team: "Richmond", position: "FWD", avg: 22.5, games: 4 },
  { name: "Nasiah Wanganeen-Milera", team: "St Kilda", position: "DEF", avg: 110.8, games: 23 },
  { name: "Rowan Marshall", team: "St Kilda", position: "RUC", avg: 105.8, games: 23 },
  { name: "Jack Sinclair", team: "St Kilda", position: "DEF", avg: 100.7, games: 23 },
  { name: "Jack Macrae", team: "St Kilda", position: "MID", avg: 90.9, games: 21 },
  { name: "Tom De Koning", team: "St Kilda", position: "RUC", avg: 84.7, games: 22 },
  { name: "Marcus Windhager", team: "St Kilda", position: "MID", avg: 82.0, games: 23 },
  { name: "Callum Wilkie", team: "St Kilda", position: "DEF", avg: 80.7, games: 23 },
  { name: "Bradley Hill", team: "St Kilda", position: "MID", avg: 74.5, games: 22 },
  { name: "Mason Wood", team: "St Kilda", position: "MID", avg: 68.7, games: 21 },
  { name: "Sam Flanders", team: "St Kilda", position: "FWD", avg: 68.3, games: 21 },
  { name: "Ryan Byrnes", team: "St Kilda", position: "DEF", avg: 71.0, games: 17 },
  { name: "Max Hall", team: "St Kilda", position: "FWD", avg: 66.1, games: 23 },
  { name: "Hugo Garcia", team: "St Kilda", position: "MID", avg: 65.5, games: 17 },
  { name: "Jack Silvagni", team: "St Kilda", position: "DEF", avg: 64.8, games: 13 },
  { name: "Darcy Wilson", team: "St Kilda", position: "MID", avg: 63.7, games: 18 },
  { name: "Cooper Sharman", team: "St Kilda", position: "FWD", avg: 63.6, games: 21 },
  { name: "Hunter Clark", team: "St Kilda", position: "MID", avg: 61.4, games: 13 },
  { name: "Mitch Owens", team: "St Kilda", position: "FWD", avg: 60.4, games: 19 },
  { name: "Mattaes Phillipou", team: "St Kilda", position: "FWD", avg: 35.9, games: 7 },
  { name: "Liam Ryan", team: "St Kilda", position: "FWD", avg: 57.1, games: 20 },
  { name: "Hugh Boxshall", team: "St Kilda", position: "MID", avg: 54.9, games: 11 },
  { name: "Anthony Caminiti", team: "St Kilda", position: "DEF", avg: 53.8, games: 23 },
  { name: "Jack Higgins", team: "St Kilda", position: "FWD", avg: 52.0, games: 23 },
  { name: "Liam Henry", team: "St Kilda", position: "FWD", avg: 30.3, games: 6 },
  { name: "Liam Stocker", team: "St Kilda", position: "DEF", avg: 46.8, games: 17 },
  { name: "Tobie Travaglia", team: "St Kilda", position: "DEF", avg: 45.6, games: 11 },
  { name: "Dougal Howard", team: "St Kilda", position: "DEF", avg: 57.3, games: 3 },
  { name: "Alixzander Tauru", team: "St Kilda", position: "DEF", avg: 42.1, games: 10 },
  { name: "Dan Butler", team: "St Kilda", position: "FWD", avg: 38.8, games: 6 },
  { name: "Isaac Keeler", team: "St Kilda", position: "FWD", avg: 36.6, games: 11 },
  { name: "Angus Hastie", team: "St Kilda", position: "DEF", avg: 37.2, games: 9 },
  { name: "Liam O'Connell", team: "St Kilda", position: "DEF", avg: 34.9, games: 7 },
  { name: "Jack Carroll", team: "St Kilda", position: "MID", avg: 21.0, games: 3 },
  { name: "Lance Collard", team: "St Kilda", position: "FWD", avg: 27.3, games: 12 },
  { name: "Alex Dodson", team: "St Kilda", position: "FWD", avg: 22.0, games: 1 },
  { name: "Brodie Grundy", team: "Sydney", position: "RUC", avg: 107.0, games: 22 },
  { name: "Errol Gulden", team: "Sydney", position: "MID", avg: 102.3, games: 10 },
  { name: "Isaac Heeney", team: "Sydney", position: "MID", avg: 96.9, games: 23 },
  { name: "Callum Mills", team: "Sydney", position: "DEF", avg: 90.0, games: 12 },
  { name: "Chad Warner", team: "Sydney", position: "MID", avg: 88.1, games: 23 },
  { name: "Nick Blakey", team: "Sydney", position: "DEF", avg: 85.0, games: 23 },
  { name: "Jake Lloyd", team: "Sydney", position: "MID", avg: 84.1, games: 22 },
  { name: "Matt Roberts", team: "Sydney", position: "DEF", avg: 82.7, games: 18 },
  { name: "James Rowbottom", team: "Sydney", position: "MID", avg: 78.5, games: 23 },
  { name: "Justin McInerney", team: "Sydney", position: "MID", avg: 78.6, games: 17 },
  { name: "Charlie Curnow", team: "Sydney", position: "FWD", avg: 65.8, games: 18 },
  { name: "Angus Sheldrick", team: "Sydney", position: "MID", avg: 62.1, games: 20 },
  { name: "Tom Papley", team: "Sydney", position: "FWD", avg: 62.0, games: 11 },
  { name: "Harry Cunningham", team: "Sydney", position: "DEF", avg: 57.8, games: 11 },
  { name: "James Jordon", team: "Sydney", position: "MID", avg: 56.9, games: 23 },
  { name: "Riley Bice", team: "Sydney", position: "DEF", avg: 56.7, games: 16 },
  { name: "Braeden Campbell", team: "Sydney", position: "FWD", avg: 56.6, games: 23 },
  { name: "Sam Wicks", team: "Sydney", position: "DEF", avg: 56.0, games: 21 },
  { name: "Tom McCartin", team: "Sydney", position: "DEF", avg: 55.6, games: 20 },
  { name: "Dane Rampe", team: "Sydney", position: "DEF", avg: 55.5, games: 21 },
  { name: "Taylor Adams", team: "Sydney", position: "FWD", avg: 35.8, games: 4 },
  { name: "Hayden McLean", team: "Sydney", position: "FWD", avg: 52.3, games: 19 },
  { name: "Joel Amartey", team: "Sydney", position: "FWD", avg: 54.1, games: 8 },
  { name: "Peter Ladhams", team: "Sydney", position: "RUC", avg: 50.9, games: 10 },
  { name: "Corey Warner", team: "Sydney", position: "MID", avg: 49.4, games: 14 },
  { name: "Caiden Cleary", team: "Sydney", position: "FWD", avg: 47.2, games: 12 },
  { name: "Lewis Melican", team: "Sydney", position: "DEF", avg: 46.0, games: 17 },
  { name: "Malcolm Rosas", team: "Sydney", position: "FWD", avg: 26.8, games: 4 },
  { name: "Joel Hamling", team: "Sydney", position: "DEF", avg: 33.1, games: 14 },
  { name: "Tom Hanily", team: "Sydney", position: "FWD", avg: 33.1, games: 8 },
  { name: "Jesse Dattoli", team: "Sydney", position: "FWD", avg: 33.0, games: 3 },
  { name: "Tom McCarthy", team: "West Coast", position: "DEF", avg: 83.5, games: 10 },
  { name: "Jack Graham", team: "West Coast", position: "MID", avg: 82.7, games: 18 },
  { name: "Liam Baker", team: "West Coast", position: "DEF", avg: 79.4, games: 23 },
  { name: "Liam Duggan", team: "West Coast", position: "DEF", avg: 79.1, games: 21 },
  { name: "Matt Flynn", team: "West Coast", position: "RUC", avg: 78.7, games: 18 },
  { name: "Ryan Maric", team: "West Coast", position: "DEF", avg: 75.2, games: 22 },
  { name: "Jake Waterman", team: "West Coast", position: "FWD", avg: 60.9, games: 8 },
  { name: "Harley Reid", team: "West Coast", position: "MID", avg: 66.7, games: 19 },
  { name: "Tom Cole", team: "West Coast", position: "DEF", avg: 66.4, games: 18 },
  { name: "Brady Hough", team: "West Coast", position: "DEF", avg: 64.1, games: 22 },
  { name: "Tim Kelly", team: "West Coast", position: "MID", avg: 63.3, games: 20 },
  { name: "Elijah Hewett", team: "West Coast", position: "MID", avg: 61.0, games: 20 },
  { name: "Jack Hutchinson", team: "West Coast", position: "MID", avg: 58.5, games: 16 },
  { name: "Jamie Cripps", team: "West Coast", position: "FWD", avg: 58.2, games: 21 },
  { name: "Reuben Ginbey", team: "West Coast", position: "DEF", avg: 55.1, games: 23 },
  { name: "Clay Hall", team: "West Coast", position: "MID", avg: 55.0, games: 13 },
  { name: "Tylar Young", team: "West Coast", position: "DEF", avg: 58.4, games: 7 },
  { name: "Bailey J. Williams", team: "West Coast", position: "RUC", avg: 52.6, games: 16 },
  { name: "Tyler Brockman", team: "West Coast", position: "FWD", avg: 49.3, games: 20 },
  { name: "Tyrell Dewar", team: "West Coast", position: "DEF", avg: 48.0, games: 16 },
  { name: "Jobe Shanahan", team: "West Coast", position: "FWD", avg: 47.9, games: 9 },
  { name: "Jack Williams", team: "West Coast", position: "FWD", avg: 46.2, games: 13 },
  { name: "Brandon Starcevich", team: "West Coast", position: "DEF", avg: 45.7, games: 10 },
  { name: "Sandy Brock", team: "West Coast", position: "DEF", avg: 44.1, games: 14 },
  { name: "Matthew Owies", team: "West Coast", position: "FWD", avg: 43.9, games: 16 },
  { name: "Rhett Bazzo", team: "West Coast", position: "DEF", avg: 47.0, games: 7 },
  { name: "Harry Edwards", team: "West Coast", position: "DEF", avg: 41.2, games: 16 },
  { name: "Lucca Grego", team: "West Coast", position: "DEF", avg: 56.0, games: 1 },
  { name: "Hamish Davis", team: "West Coast", position: "MID", avg: 43.0, games: 8 },
  { name: "Archer Reid", team: "West Coast", position: "FWD", avg: 35.7, games: 14 },
  { name: "Noah Long", team: "West Coast", position: "FWD", avg: 34.2, games: 10 },
  { name: "Tom Gross", team: "West Coast", position: "MID", avg: 34.9, games: 8 },
  { name: "Harry Schoenberg", team: "West Coast", position: "MID", avg: 23.0, games: 1 },
  { name: "Bo Allan", team: "West Coast", position: "DEF", avg: 26.7, games: 6 },
  { name: "Deven Robertson", team: "West Coast", position: "FWD", avg: 15.5, games: 4 },
  { name: "Jacob Newton", team: "West Coast", position: "FWD", avg: 24.0, games: 2 },
  { name: "Malakai Champion", team: "West Coast", position: "FWD", avg: 20.5, games: 2 },
  { name: "Marcus Bontempelli", team: "Western Bulldogs", position: "MID", avg: 111.3, games: 18 },
  { name: "Tim English", team: "Western Bulldogs", position: "RUC", avg: 110.7, games: 23 },
  { name: "Tom Liberatore", team: "Western Bulldogs", position: "MID", avg: 99.6, games: 23 },
  { name: "Ed Richards", team: "Western Bulldogs", position: "MID", avg: 96.7, games: 23 },
  { name: "Matthew Kennedy", team: "Western Bulldogs", position: "MID", avg: 96.5, games: 23 },
  { name: "Bailey Dale", team: "Western Bulldogs", position: "DEF", avg: 92.0, games: 23 },
  { name: "Adam Treloar", team: "Western Bulldogs", position: "MID", avg: 69.8, games: 4 },
  { name: "Sam Darcy", team: "Western Bulldogs", position: "FWD", avg: 82.2, games: 17 },
  { name: "Bailey Williams", team: "Western Bulldogs", position: "DEF", avg: 76.8, games: 23 },
  { name: "Aaron Naughton", team: "Western Bulldogs", position: "FWD", avg: 71.8, games: 23 },
  { name: "Joel Freijah", team: "Western Bulldogs", position: "MID", avg: 71.3, games: 23 },
  { name: "James Harmes", team: "Western Bulldogs", position: "MID", avg: 66.8, games: 13 },
  { name: "Lachlan Bramble", team: "Western Bulldogs", position: "DEF", avg: 66.3, games: 23 },
  { name: "Ryley Sanders", team: "Western Bulldogs", position: "MID", avg: 66.1, games: 21 },
  { name: "Sam Davidson", team: "Western Bulldogs", position: "MID", avg: 66.1, games: 19 },
  { name: "Rhylee West", team: "Western Bulldogs", position: "FWD", avg: 65.6, games: 23 },
  { name: "Riley Garcia", team: "Western Bulldogs", position: "MID", avg: 53.5, games: 8 },
  { name: "Oskar Baker", team: "Western Bulldogs", position: "DEF", avg: 58.0, games: 9 },
  { name: "Rory Lobb", team: "Western Bulldogs", position: "DEF", avg: 55.1, games: 23 },
  { name: "Luke Cleary", team: "Western Bulldogs", position: "DEF", avg: 51.8, games: 16 },
  { name: "Connor Budarick", team: "Western Bulldogs", position: "FWD", avg: 48.2, games: 17 },
  { name: "Buku Khamis", team: "Western Bulldogs", position: "DEF", avg: 47.7, games: 14 },
  { name: "Harvey Gallagher", team: "Western Bulldogs", position: "DEF", avg: 41.8, games: 5 },
  { name: "James O'Donnell", team: "Western Bulldogs", position: "DEF", avg: 45.8, games: 22 },
  { name: "Jordan Croft", team: "Western Bulldogs", position: "FWD", avg: 60.0, games: 2 },
  { name: "Nick Coffield", team: "Western Bulldogs", position: "DEF", avg: 55.0, games: 4 },
  { name: "Laitham Vandermeer", team: "Western Bulldogs", position: "FWD", avg: 43.4, games: 19 },
  { name: "Lachlan McNeil", team: "Western Bulldogs", position: "FWD", avg: 42.4, games: 20 },
  { name: "Jedd Busslinger", team: "Western Bulldogs", position: "DEF", avg: 36.4, games: 7 },
  { name: "Arthur Jones", team: "Western Bulldogs", position: "MID", avg: 20.0, games: 4 },
  { name: "Josh Dolan", team: "Western Bulldogs", position: "FWD", avg: 27.5, games: 11 },
  { name: "Cooper Hynes", team: "Western Bulldogs", position: "FWD", avg: 27.1, games: 8 },
  { name: "Ryan Gardner", team: "Western Bulldogs", position: "DEF", avg: 26.0, games: 1 },
]

// Map position strings to Position enum values
function parsePositions(posStr: string): string[] {
  const mapping: Record<string, string> = {
    'DEF': 'DEF',
    'MID': 'MID',
    'RUC': 'RUC',
    'FWD': 'FWD',
  }
  return posStr.split('/').map(p => mapping[p.trim()]).filter(Boolean)
}

async function main() {
  console.log('🏈 Importing 2026 AFL Players...\n')

  // Get AFL teams
  const teams = await prisma.aflTeam.findMany()
  const teamMap = new Map(teams.map(t => [t.name, t.id]))

  // Get draft round (first round of the season)
  const season = await prisma.season.findFirst({ where: { year: 2026 } })
  if (!season) {
    console.error('No 2026 season found!')
    return
  }

  const draftRound = await prisma.round.findFirst({
    where: { seasonId: season.id, roundNumber: 1 }
  })
  if (!draftRound) {
    console.error('No round 1 found!')
    return
  }

  // Clear existing players and all related records
  console.log('🧹 Clearing existing players...')
  await prisma.negotiationMessage.deleteMany()
  await prisma.negotiationSession.deleteMany({ where: { aflPlayerId: { not: null } } })
  await prisma.personalityProfile.deleteMany({ where: { aflPlayerId: { not: null } } })
  await prisma.contractOffer.deleteMany()
  await prisma.matchPlayerScore.deleteMany()
  await prisma.contract.deleteMany()
  await prisma.draftEligibility.deleteMany()
  await prisma.aflPlayer.deleteMany()

  // Prepare batch data
  console.log('👤 Creating players (batch)...')
  const playerData = players
    .filter(p => teamMap.has(p.team))
    .map(player => {
      const nameParts = player.name.split(' ')
      return {
        firstName: nameParts[0],
        lastName: nameParts.slice(1).join(' '),
        positions: parsePositions(player.position),
        aflTeamId: teamMap.get(player.team)!,
        status: 'ACTIVE' as const,
        isAvailable: false,
        avgPoints: player.avg,
        gamesPlayed: player.games,
      }
    })

  // Batch insert all players
  await prisma.aflPlayer.createMany({ data: playerData })
  console.log(`✅ Created ${playerData.length} players`)

  // Get all created players to create eligibility records
  console.log('📋 Creating draft eligibility...')
  const createdPlayers = await prisma.aflPlayer.findMany({
    select: { id: true, firstName: true, lastName: true, gamesPlayed: true }
  })

  const eligibilityData = createdPlayers
    .filter(p => (p.gamesPlayed ?? 0) > 0)
    .map(p => ({
      aflPlayerId: p.id,
      roundId: draftRound.id,
      isEligible: true,
      seniorGames: p.gamesPlayed ?? 0,
      isRookie: (p.gamesPlayed ?? 0) < 10,
    }))

  await prisma.draftEligibility.createMany({ data: eligibilityData })
  console.log(`✅ ${eligibilityData.length} players are draft eligible`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
